In [5]:
import pandas as pd
df= pd.read_csv("train.csv")

In [6]:
# 欠損データの確認
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [20]:
# Embarked, Ageに欠損のあるサンプルを削除
df_1 = df.dropna(subset=["Embarked","Age"])

In [25]:
# pandasでone-hotエンコーディングを使い、ダミー変数を作成
sex_dum = pd.get_dummies(df_1["Sex"])
emb_dum = pd.get_dummies(df_1["Embarked"])

In [26]:
X = pd.concat([df_1.iloc[:,[2,5,6,7,9]], sex_dum, emb_dum], axis=1)

In [27]:
y = df_1.iloc[:,1]

In [28]:
X

     Pclass   Age  SibSp  Parch      Fare  female  male  C  Q  S
0         3  22.0      1      0    7.2500       0     1  0  0  1
1         1  38.0      1      0   71.2833       1     0  1  0  0
2         3  26.0      0      0    7.9250       1     0  0  0  1
3         1  35.0      1      0   53.1000       1     0  0  0  1
4         3  35.0      0      0    8.0500       0     1  0  0  1
6         1  54.0      0      0   51.8625       0     1  0  0  1
7         3   2.0      3      1   21.0750       0     1  0  0  1
8         3  27.0      0      2   11.1333       1     0  0  0  1
9         2  14.0      1      0   30.0708       1     0  1  0  0
10        3   4.0      1      1   16.7000       1     0  0  0  1
11        1  58.0      0      0   26.5500       1     0  0  0  1
12        3  20.0      0      0    8.0500       0     1  0  0  1
13        3  39.0      1      5   31.2750       0     1  0  0  1
14        3  14.0      0      0    7.8542       1     0  0  0  1
15        2  55.0      0      0   16.0000       1     0  0  0  1
16        3   2.0      4      1   29.1250       0     1  0  1  0
18        3  31.0      1      0   18.0000       1     0  0  0  1
20        2  35.0      0      0   26.0000       0     1  0  0  1
21        2  34.0      0      0   13.0000       0     1  0  0  1
22        3  15.0      0      0    8.0292       1     0  0  1  0
23        1  28.0      0      0   35.5000       0     1  0  0  1
24        3   8.0      3      1   21.0750       1     0  0  0  1
25        3  38.0      1      5   31.3875       1     0  0  0  1
27        1  19.0      3      2  263.0000       0     1  0  0  1
30        1  40.0      0      0   27.7208       0     1  1  0  0
33        2  66.0      0      0   10.5000       0     1  0  0  1
34        1  28.0      1      0   82.1708       0     1  1  0  0
35        1  42.0      1      0   52.0000       0     1  0  0  1
37        3  21.0      0      0    8.0500       0     1  0  0  1
38        3  18.0      2      0   18.0000       1     0  0  0  1
..      ...   ...    ...    ...       ...     ...   ... .. .. ..
856       1  45.0      1      1  164.8667       1     0  0  0  1
857       1  51.0      0      0   26.5500       0     1  0  0  1
858       3  24.0      0      3   19.2583       1     0  1  0  0
860       3  41.0      2      0   14.1083       0     1  0  0  1
861       2  21.0      1      0   11.5000       0     1  0  0  1
862       1  48.0      0      0   25.9292       1     0  0  0  1
864       2  24.0      0      0   13.0000       0     1  0  0  1
865       2  42.0      0      0   13.0000       1     0  0  0  1
866       2  27.0      1      0   13.8583       1     0  1  0  0
867       1  31.0      0      0   50.4958       0     1  0  0  1
869       3   4.0      1      1   11.1333       0     1  0  0  1
870       3  26.0      0      0    7.8958       0     1  0  0  1
871       1  47.0      1      1   52.5542       1     0  0  0  1
872       1  33.0      0      0    5.0000       0     1  0  0  1
873       3  47.0      0      0    9.0000       0     1  0  0  1
874       2  28.0      1      0   24.0000       1     0  1  0  0
875       3  15.0      0      0    7.2250       1     0  1  0  0
876       3  20.0      0      0    9.8458       0     1  0  0  1
877       3  19.0      0      0    7.8958       0     1  0  0  1
879       1  56.0      0      1   83.1583       1     0  1  0  0
880       2  25.0      0      1   26.0000       1     0  0  0  1
881       3  33.0      0      0    7.8958       0     1  0  0  1
882       3  22.0      0      0   10.5167       1     0  0  0  1
883       2  28.0      0      0   10.5000       0     1  0  0  1
884       3  25.0      0      0    7.0500       0     1  0  0  1
885       3  39.0      0      5   29.1250       1     0  0  1  0
886       2  27.0      0      0   13.0000       0     1  0  0  1
887       1  19.0      0      0   30.0000       1     0  0  0  1
889       1  26.0      0      0   30.0000       0     1  1  0  0
890       3  32.0      0      0    7.7500       0     1  0  1  0

[712 rows x 10 columns]

In [29]:
# ホールドアウト法による分割
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [35]:
# ランダムフォレストによる学習
from sklearn.ensemble import RandomForestClassifier
rfc_1 = RandomForestClassifier(random_state=0, n_estimators=10)
rfc_1.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [36]:
# 正答率を出力
print('train accuracy: %.3f' % rfc_1.score(X_train, y_train))
print('test  accuracy: %.3f' % rfc_1.score(X_test, y_test))

train accuracy: 0.976
test  accuracy: 0.762